const storage = { get: (key, fallback) => JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)), set: (key, value) => localStorage.setItem(key, JSON.stringify(value)) };
const $ = (selector) => document.querySelector(selector);
document.querySelector('main').insertAdjacentHTML('beforeend', `<section class="screen" id="eventos"><div class="page-title"><p class="eyebrow">PRONTUÁRIO MÉDICO</p><h1>Eventos de saúde</h1><p>Registre monitoramentos diários, atendimentos, sintomas, diagnósticos e exames.</p></div><form id="health-event-form" class="panel form-grid"><label>Data do evento<input id="health-event-date" type="date" required /></label><label>Tipo de evento<select id="health-event-type"><option>Monitoramento diário</option><option>Consulta</option><option>Emergência</option><option>Internação</option><option>Exame</option><option>Procedimento</option><option>Outro</option></select></label><label class="wide">Descrição do evento<textarea id="health-event-description" required placeholder="Ex.: Pressão 12/8 às 8h; temperatura 36,5 °C."></textarea></label><label>Médico(a)<input id="health-event-doctor" placeholder="Nome do profissional" /></label><label>Diagnóstico<input id="health-event-diagnosis" placeholder="Ex.: Hipertensão arterial" /></label><label class="wide">Exames solicitados / orientações<textarea id="health-event-exams" placeholder="Ex.: Repetir a medição à noite e observar sintomas."></textarea></label><button class="primary wide">Adicionar ao prontuário</button></form></section>`);
$('#health-event-form').insertAdjacentHTML('afterbegin', '<input id="health-event-edit-id" type="hidden" />');
const healthEventSubmit = $('#health-event-form .primary'); healthEventSubmit.id = 'health-event-submit';
healthEventSubmit.insertAdjacentHTML('afterend', '<button id="cancel-health-event-edit" class="secondary-button wide" type="button" hidden>Cancelar edição</button>');
$('#health-event-form').insertAdjacentHTML('afterend', '<section class="medical-record"><div class="section-heading"><div><p class="eyebrow">EVENTOS REGISTRADOS</p><h2>Prontuário</h2></div></div><div id="health-event-list" class="list-stack"></div></section>');
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('visible'); setTimeout(() => el.classList.remove('visible'), 2600); };

function showScreen(id) {
  document.querySelectorAll('.screen').forEach((screen) => screen.classList.toggle('active', screen.id === id));
  document.querySelectorAll('[data-screen]').forEach((button) => button.classList.toggle('nav-active', button.dataset.screen === id && button.closest('.bottom-nav')));
  window.scrollTo({ top: 0, behavior: 'smooth' });
}
document.addEventListener('click', (event) => { const target = event.target.closest('[data-screen]'); if (target) showScreen(target.dataset.screen); });

function formatDate(date, time = '') { if (!date) return 'Data a definir'; const value = new Date(`${date}T12:00:00`); return `${value.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })}${time ? ` · ${time}` : ''}`; }
function escapeHtml(value = '') { const item = document.createElement('div'); item.textContent = value; return item.innerHTML; }
let timelineEvents = [];
function timelineDateValue(value) { const date = String(value || '').slice(0, 10); return new Date(`${date}T12:00:00`).getTime() || 0; }
function renderTimeline() {
  const events = [];
  storage.get('vitalink-health-events', []).forEach((item) => events.push({ id: `health-${item.id}`, source: 'health', date: item.date || item.createdAt, type: item.type || 'Evento de saúde', title: item.description, doctor: item.doctor, diagnosis: item.diagnosis, exams: item.exams, documents: item.documents || [], detail: 'Evento registrado no prontuário.' }));
  storage.get('vitalink-appointments', []).forEach((item) => events.push({ id: `appointment-${item.id}`, source: 'appointment', date: item.date || item.createdAt, type: 'Agenda', title: item.title, time: item.time, documents: [], detail: item.time ? `Horário: ${item.time}` : 'Horário a definir.' }));
  timelineEvents = events.sort((a, b) => timelineDateValue(a.date) - timelineDateValue(b.date));
  const filter = $('#timeline-filter')?.value || 'all';
  const visible = timelineEvents.filter((item) => filter === 'all' || item.source === filter);
  const list = $('#timeline-list');
  const detail = $('#timeline-detail');
  if (!visible.length) { list.innerHTML = '<div class="empty-state">Nenhum evento encontrado. Cadastre um evento de saúde para iniciar a linha do tempo.</div>'; detail.hidden = true; return; }
  list.innerHTML = `<div class="timeline-scroll"><div class="timeline-track">${visible.map((item, index) => { const year = new Date(`${String(item.date).slice(0, 10)}T12:00:00`).getFullYear(); return `<article class="timeline-event ${index % 2 ? 'below' : 'above'}"><div class="timeline-card"><span>${escapeHtml(item.type)}</span><strong>${escapeHtml(item.title)}</strong><small>${formatDate(item.date, item.time)}</small></div><button class="timeline-dot" type="button" data-timeline-id="${escapeHtml(item.id)}" aria-label="Abrir ${escapeHtml(item.title)}" aria-pressed="false"></button><time>${year}</time></article>`; }).join('')}</div></div><p class="timeline-hint">Selecione um marco para consultar as informações do evento.</p>`;
  showTimelineDetail(visible[visible.length - 1].id);
}
function showTimelineDetail(id) {
  const item = timelineEvents.find((event) => event.id === id); if (!item) return;
  document.querySelectorAll('[data-timeline-id]').forEach((button) => { const active = button.dataset.timelineId === id; button.classList.toggle('active', active); button.setAttribute('aria-pressed', String(active)); });
  const fields = [["Médico(a)", item.doctor], ['Diagnóstico', item.diagnosis], ['Exames e orientações', item.exams]].filter(([, value]) => value);
  const documents = item.documents?.length ? `<div class="timeline-documents"><strong>Documentos relacionados</strong><div>${item.documents.map((name) => `<button type="button" data-screen="documentos">▤ ${escapeHtml(name)}</button>`).join('')}</div></div>` : '<p class="timeline-no-docs">Nenhum documento relacionado a este evento.</p>';
  const detail = $('#timeline-detail'); detail.hidden = false; detail.innerHTML = `<div class="timeline-detail-heading"><div><p class="eyebrow">${escapeHtml(item.type)}</p><h2>${escapeHtml(item.title)}</h2><span>${formatDate(item.date, item.time)}</span></div><button class="secondary-button" type="button" data-screen="eventos">Abrir prontuário</button></div>${fields.length ? `<dl>${fields.map(([label, value]) => `<div><dt>${label}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl>` : `<p class="timeline-detail-copy">${escapeHtml(item.detail)}</p>`}${documents}`;
}
document.addEventListener('click', (event) => { const button = event.target.closest('[data-timeline-id]'); if (button) showTimelineDetail(button.dataset.timelineId); });
$('#timeline-filter').addEventListener('change', renderTimeline);

function renderAppointments() {
  const appointments = storage.get('vitalink-appointments', []).sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const list = $('#appointment-list');
  list.innerHTML = appointments.length ? appointments.map((a) => `<article class="list-item appointment-record"><div class="event-date">${formatDate(a.date).replace(' de ', '<br>')}</div><div class="list-main"><strong>${escapeHtml(a.title)}</strong><span>${a.time || 'Horário a definir'}${a.specialty ? ` · ${escapeHtml(a.specialty)}` : ''}</span>${a.doctor ? `<small>Médico(a): ${escapeHtml(a.doctor)}</small>` : ''}${a.location ? `<small>Local: ${escapeHtml(a.location)}${a.contact ? ` · ${escapeHtml(a.contact)}` : ''}</small>` : a.contact ? `<small>Contato: ${escapeHtml(a.contact)}</small>` : ''}</div><button class="icon-button" data-delete-appointment="${a.id}" aria-label="Excluir evento">×</button></article>`).join('') : '<div class="empty-state">Nenhuma consulta ou exame cadastrado.</div>';
  const today = new Date(); today.setHours(0, 0, 0, 0); const end = new Date(today); end.setDate(end.getDate() + 7);
  const week = appointments.filter((item) => { const date = new Date(`${item.date}T12:00:00`); return date >= today && date < end; });
  $('#week-appointments').innerHTML = week.length ? week.map((item) => `<button type="button" data-screen="agenda"><strong>${escapeHtml(item.title)}</strong><span>${formatDate(item.date, item.time)}${item.specialty ? ` · ${escapeHtml(item.specialty)}` : ''}${item.doctor ? ` · ${escapeHtml(item.doctor)}` : ''}</span></button>`).join('') : '<span>Nenhum compromisso nesta semana.</span>';
}
$('#appointment-form').addEventListener('submit', (event) => { event.preventDefault(); const title = $('#appointment-title').value.trim(); const date = $('#appointment-date').value; if (!title || !date) return; const list = storage.get('vitalink-appointments', []); list.push({ id: Date.now(), createdAt: new Date().toISOString(), title, specialty: $('#appointment-specialty').value.trim(), doctor: $('#appointment-doctor').value.trim(), date, time: $('#appointment-time').value, location: $('#appointment-location').value.trim(), contact: $('#appointment-contact').value.trim() }); storage.set('vitalink-appointments', list); event.target.reset(); renderAppointments(); renderTimeline(); toast('Evento adicionado à agenda.'); });
document.addEventListener('click', (event) => { const button = event.target.closest('[data-delete-appointment]'); if (!button) return; storage.set('vitalink-appointments', storage.get('vitalink-appointments', []).filter((a) => a.id !== Number(button.dataset.deleteAppointment))); renderAppointments(); toast('Evento removido.'); });

const importedMedicines = [['Manhã','1','Benzilato de anlodipino','5 mg','1 comprimido','Pressão','Dra. Larissa'],['Manhã','11','Rosuvastatina + ezetimiba (Plenance Eze)','10 + 10 mg','1 comprimido','Colesterol','Dra. Liliane (Baía Sul)'],['Manhã','15','BUP XL','150 mg','1 comprimido','Antidepressivo','Dra. Larissa'],['Manhã','16','Colecalciferol (Vitamina D)','1.000 UI','1 comprimido contínuo','Vitamina D','Dra. Larissa'],['Noite','3','Ácido acetilsalicílico','100 mg','1 comprimido','Diminuir o risco de coágulos','Dra. Larissa'],['Noite','4','Mirabregona','50 mg','1 comprimido','Bexiga hiperativa','Dr. Márcio Ikeda'],['Noite','5','Solifilacina','5 mg','1 comprimido','Bexiga hiperativa','Dr. Márcio Ikeda'],['Noite','6','Dutasterida','0,5 mg','1 comprimido','Diminuição da próstata','Dr. Márcio Ikeda'],['Noite','7','Cloridrato de memantina (receita controlada)','10 mg','2 comprimidos','Tratamento do Alzheimer','Dra. Larissa'],['Noite','8','Donepezila (receita controlada)','10 mg','1 comprimido','Tratamento do Alzheimer','Dra. Larissa'],['Noite','10','Mecobalamina (até 12/12/26)','1.000 mcg','1 comprimido','Reposição de vitamina B12','Dra. Larissa'],['Noite','12','Losartana potássica','50 mg','1 comprimido','Hipertensão','Dra. Liliane (Baía Sul)'],['Noite','17','Melatonina','5 mg','1 comprimido','Distúrbio do sono','Dra. Larissa']];
if (!localStorage.getItem('vitalink-medication-document-imported')) { const medicines = storage.get('vitalink-medicines', []); storage.set('vitalink-medicines', [...medicines, ...importedMedicines.map(([period, box, name, dosage, quantity, purpose, doctor], index) => ({ id: 20260612000 + index, createdAt: '2026-06-12T12:00:00', period, box, name, dosage, quantity, purpose, doctor, stockQty: '', dailyUse: quantity.startsWith('2') ? 2 : 1, stockDate: '', purchaseLead: 7 }))]); localStorage.setItem('vitalink-medication-document-imported', 'true'); }
if (!localStorage.getItem('vitalink-stock-control-v1')) { storage.set('vitalink-medicines', storage.get('vitalink-medicines', []).map((m) => ({ ...m, stockQty: m.stockQty ?? '', dailyUse: m.dailyUse ?? (String(m.quantity || '').startsWith('2') ? 2 : 1), stockDate: m.stockDate ?? '', purchaseLead: m.purchaseLead ?? 7 }))); localStorage.setItem('vitalink-stock-control-v1', 'true'); }
function formatInventoryDate(date) { return date ? date.toLocaleDateString('pt-BR') : '—'; }
function getInventoryStatus(medicine) { const stock = Number(medicine.stockQty); const daily = Number(medicine.dailyUse); if (medicine.stockQty === '' || medicine.stockQty === undefined || !Number.isFinite(stock) || !Number.isFinite(daily) || stock < 0 || daily <= 0) return null; const start = medicine.stockDate ? new Date(`${medicine.stockDate}T12:00:00`) : new Date(); const days = Math.ceil(stock / daily); const end = new Date(start); end.setDate(end.getDate() + days); const buy = new Date(end); buy.setDate(buy.getDate() - Number(medicine.purchaseLead ?? 7)); const today = new Date(); today.setHours(0, 0, 0, 0); const week = new Date(today); week.setDate(week.getDate() + 7); const status = buy <= today ? 'Comprar agora' : buy <= week ? 'Comprar esta semana' : 'Em dia'; return { stock, daily, end, buy, status }; }
function todayKey() { return new Date().toISOString().slice(0, 10); }
function renderTodayMedicines(medicines = storage.get('vitalink-medicines', [])) { const taken = storage.get(`vitalink-medicine-taken-${todayKey()}`, []); $('#today-medicines').innerHTML = medicines.length ? medicines.map((medicine) => { const checked = taken.map(String).includes(String(medicine.id)); return `<label class="today-medicine ${checked ? 'taken' : ''}"><input type="checkbox" data-taken-medicine="${medicine.id}" ${checked ? 'checked' : ''} /><span><strong>${escapeHtml(medicine.name)}</strong><small>${escapeHtml(medicine.period || 'Horário não informado')}${medicine.dosage ? ` · ${escapeHtml(medicine.dosage)}` : ''}</small></span></label>`; }).join('') : '<span>Nenhum medicamento cadastrado.</span>'; }
function renderMedicines() { const medicines = storage.get('vitalink-medicines', []); renderTodayMedicines(medicines); $('#medicine-list').innerHTML = medicines.length ? medicines.map((m) => { const inventory = getInventoryStatus(m); return `<tr><td><span class="medicine-pill">${escapeHtml(m.period || 'Sem período')}</span></td><td><strong>${escapeHtml(m.name)}</strong></td><td>${escapeHtml(m.dosage || '—')}</td><td>${escapeHtml(m.quantity || '—')}</td><td>${escapeHtml(m.purpose || '—')}</td><td>${escapeHtml(m.doctor || '—')}</td><td class="stock-editor"><input type="number" min="0" step="1" value="${m.stockQty ?? ''}" placeholder="Unidades" data-stock-field="stockQty" data-medicine-id="${m.id}" /><input type="date" value="${m.stockDate || ''}" data-stock-field="stockDate" data-medicine-id="${m.id}" /></td><td><input class="daily-input" type="number" min="0.25" step="0.25" value="${m.dailyUse ?? ''}" placeholder="Un./dia" data-stock-field="dailyUse" data-medicine-id="${m.id}" /></td><td>${inventory ? formatInventoryDate(inventory.end) : '—'}</td><td>${inventory ? formatInventoryDate(inventory.buy) : '—'}</td><td>${inventory ? `<span class="stock-status ${inventory.status === 'Em dia' ? 'ok' : 'attention'}">${inventory.status}</span>` : `<button class="stock-status neutral stock-action" type="button" data-inform-stock="${m.id}">Informar estoque</button>`}</td><td><button class="icon-button" data-delete-medicine="${m.id}" aria-label="Excluir medicamento">×</button></td></tr>`; }).join('') : '<tr><td colspan="12" class="empty-state">Nenhum medicamento cadastrado.</td></tr>'; }
$('#medicine-form').addEventListener('submit', (event) => { event.preventDefault(); const name = $('#medicine-name').value.trim(); if (!name) return; const list = storage.get('vitalink-medicines', []); list.push({ id: Date.now(), createdAt: new Date().toISOString(), period: $('#period').value, name, dosage: $('#dosage').value.trim(), quantity: $('#quantity').value.trim(), stockQty: $('#stock-quantity').value, dailyUse: $('#daily-use').value, stockDate: $('#stock-date').value, purchaseLead: $('#purchase-lead').value || 7, purpose: $('#purpose').value.trim(), doctor: $('#doctor').value.trim() }); storage.set('vitalink-medicines', list); event.target.reset(); $('#purchase-lead').value = 7; renderMedicines(); renderTimeline(); toast('Medicamento adicionado.'); });
document.addEventListener('change', (event) => { const input = event.target.closest('[data-stock-field]'); if (!input) return; const medicines = storage.get('vitalink-medicines', []).map((medicine) => String(medicine.id) === input.dataset.medicineId ? { ...medicine, [input.dataset.stockField]: input.value } : medicine); storage.set('vitalink-medicines', medicines); renderMedicines(); });
function medicineDoseUnits(medicine) { const match = String(medicine.quantity || '').replace(',', '.').match(/\d+(?:\.\d+)?/); const value = match ? Number(match[0]) : 1; return Number.isFinite(value) && value > 0 ? value : 1; }
document.addEventListener('change', (event) => { const input = event.target.closest('[data-taken-medicine]'); if (!input) return; const key = `vitalink-medicine-taken-${todayKey()}`; const current = storage.get(key, []).map(String); const id = input.dataset.takenMedicine; const wasTaken = current.includes(id); if (input.checked === wasTaken) return; storage.set(key, input.checked ? [...new Set([...current, id])] : current.filter((item) => item !== id)); const medicines = storage.get('vitalink-medicines', []).map((medicine) => { if (String(medicine.id) !== id || medicine.stockQty === '' || medicine.stockQty === undefined) return medicine; const stock = Number(medicine.stockQty); if (!Number.isFinite(stock)) return medicine; const dose = medicineDoseUnits(medicine); return { ...medicine, stockQty: String(input.checked ? Math.max(0, stock - dose) : stock + dose) }; }); storage.set('vitalink-medicines', medicines); renderMedicines(); toast(input.checked ? 'Medicamento administrado e estoque atualizado.' : 'Marcação removida e estoque devolvido.'); });
document.addEventListener('click', (event) => { const button = event.target.closest('[data-inform-stock]'); if (!button) return; const field = document.querySelector(`[data-stock-field="stockQty"][data-medicine-id="${button.dataset.informStock}"]`); field?.focus(); field?.scrollIntoView({ behavior: 'smooth', block: 'center' }); });
$('#print-shopping-list').addEventListener('click', () => { const week = storage.get('vitalink-medicines', []).filter((m) => { const inventory = getInventoryStatus(m); return inventory && inventory.status !== 'Em dia'; }); const rows = week.length ? week.map((m) => { const inventory = getInventoryStatus(m); return `<tr><td>${escapeHtml(m.name)}</td><td>${formatInventoryDate(inventory.buy)}</td><td>${inventory.stock} un.</td><td>${inventory.daily} un./dia</td></tr>`; }).join('') : '<tr><td colspan="4">Nenhum medicamento precisa ser comprado nesta semana.</td></tr>'; const popup = window.open('', '_blank'); if (!popup) return toast('Permita a abertura da janela de impressão.'); popup.document.write(`<!doctype html><html lang="pt-BR"><head><title>VitaLink - Lista de compras</title><style>body{font-family:Arial,sans-serif;color:#183b42;padding:32px}h1{color:#197f85}table{width:100%;border-collapse:collapse}th,td{padding:10px;border:1px solid #cfe0e0;text-align:left}th{background:#e7f7f5}</style></head><body><h1>VitaLink · Compras da semana</h1><p>Medicamentos com compra prevista para os próximos 7 dias.</p><table><thead><tr><th>Medicamento</th><th>Data para compra</th><th>Estoque</th><th>Consumo</th></tr></thead><tbody>${rows}</tbody></table></body></html>`); popup.document.close(); popup.focus(); popup.print(); });
document.addEventListener('click', (event) => { const button = event.target.closest('[data-delete-medicine]'); if (!button) return; storage.set('vitalink-medicines', storage.get('vitalink-medicines', []).filter((m) => m.id !== Number(button.dataset.deleteMedicine))); renderMedicines(); toast('Medicamento removido.'); });

function renderFiles() { const files = storage.get('vitalink-files', []); $('#file-list').innerHTML = files.length ? files.map((file) => `<article class="list-item"><span class="quick-icon lavender">▤</span><div class="list-main"><strong>${escapeHtml(file.name)}</strong><span>${escapeHtml(file.size)} · ${file.data ? 'Disponível para abrir' : 'Arquivo de versão anterior indisponível'}</span></div>${file.data ? `<button class="secondary-button" type="button" data-open-file="${file.id}">Abrir</button>` : ''}<button class="icon-button" data-delete-file="${file.id}" aria-label="Excluir documento">×</button></article>`).join('') : '<div class="empty-state">Nenhum documento selecionado ainda.</div>'; }
function fileToDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.addEventListener('load', () => resolve(reader.result)); reader.addEventListener('error', reject); reader.readAsDataURL(file); }); }
$('#file-upload').addEventListener('change', async (event) => { const selected = [...event.target.files]; if (selected.some((file) => file.size > 3 * 1024 * 1024)) { event.target.value = ''; toast('Cada documento deve ter no máximo 3 MB nesta versão.'); return; } try { const added = await Promise.all(selected.map(async (file) => ({ id: Date.now() + Math.random(), createdAt: new Date().toISOString(), name: file.name, type: file.type || 'application/octet-stream', size: `${Math.max(1, Math.round(file.size / 1024))} KB`, data: await fileToDataUrl(file) }))); storage.set('vitalink-files', [...storage.get('vitalink-files', []), ...added]); event.target.value = ''; renderFiles(); renderTimeline(); toast('Documento adicionado à biblioteca.'); } catch (error) { toast('Não foi possível armazenar o documento.'); } });
document.addEventListener('click', (event) => { const button = event.target.closest('[data-open-file]'); if (!button) return; const file = storage.get('vitalink-files', []).find((item) => String(item.id) === button.dataset.openFile); if (!file?.data) return toast('Este documento precisa ser adicionado novamente.'); const link = document.createElement('a'); link.href = file.data; link.target = '_blank'; link.rel = 'noopener'; link.download = file.type === 'application/pdf' ? '' : file.name; document.body.appendChild(link); link.click(); link.remove(); });
document.addEventListener('click', (event) => { const button = event.target.closest('[data-delete-file]'); if (!button) return; storage.set('vitalink-files', storage.get('vitalink-files', []).filter((f) => String(f.id) !== button.dataset.deleteFile)); renderFiles(); renderEventDocumentChoices(); toast('Documento removido.'); });
function renderEventDocumentChoices() {}
function renderHealthEvents() { const records = storage.get('vitalink-health-events', []).sort((a, b) => timelineDateValue(b.date) - timelineDateValue(a.date)); $('#health-event-list').innerHTML = records.length ? records.map((item) => `<article class="list-item health-event-record"><div class="event-date">${formatDate(item.date).replace(' de ', '<br>')}</div><div class="list-main"><strong>${escapeHtml(item.description)}</strong><span>${escapeHtml(item.type || 'Evento de saúde')}${item.diagnosis ? ` · ${escapeHtml(item.diagnosis)}` : ''}</span></div><button class="secondary-button" type="button" data-edit-health-event="${item.id}">Editar</button></article>`).join('') : '<div class="empty-state">Nenhum evento de saúde registrado.</div>'; }
function resetHealthEventForm() { $('#health-event-form').reset(); $('#health-event-edit-id').value = ''; $('#health-event-date').value = todayKey(); $('#health-event-submit').textContent = 'Adicionar ao prontuário'; $('#cancel-health-event-edit').hidden = true; }
function editHealthEvent(id) { const item = storage.get('vitalink-health-events', []).find((record) => String(record.id) === String(id)); if (!item) return; $('#health-event-edit-id').value = item.id; $('#health-event-date').value = item.date || ''; $('#health-event-type').value = item.type || 'Consulta'; $('#health-event-description').value = item.description || ''; $('#health-event-doctor').value = item.doctor || ''; $('#health-event-diagnosis').value = item.diagnosis || ''; $('#health-event-exams').value = item.exams || ''; $('#health-event-submit').textContent = 'Salvar alterações'; $('#cancel-health-event-edit').hidden = false; $('#health-event-form').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
document.addEventListener('click', (event) => { const button = event.target.closest('[data-edit-health-event]'); if (button) editHealthEvent(button.dataset.editHealthEvent); });
$('#cancel-health-event-edit').addEventListener('click', resetHealthEventForm);
$('#health-event-form').addEventListener('submit', (event) => { event.preventDefault(); const editId = $('#health-event-edit-id').value; const id = editId ? Number(editId) : Date.now(); const records = storage.get('vitalink-health-events', []); const existing = records.find((record) => String(record.id) === String(id)); const updated = { id, createdAt: existing?.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString(), date: $('#health-event-date').value, type: $('#health-event-type').value, description: $('#health-event-description').value.trim(), doctor: $('#health-event-doctor').value.trim(), diagnosis: $('#health-event-diagnosis').value.trim(), exams: $('#health-event-exams').value.trim(), documents: existing?.documents || [] }; storage.set('vitalink-health-events', editId ? records.map((record) => String(record.id) === String(id) ? updated : record) : [...records, updated]); resetHealthEventForm(); renderHealthEvents(); renderTimeline(); toast(editId ? 'Evento atualizado.' : 'Evento adicionado ao prontuário.'); });

const profile = storage.get('vitalink-profile', {}); let profilePhoto = profile.photo || ''; const CFM_SPECIALTIES = ['Acupuntura','Alergia e imunologia','Anestesiologia','Angiologia','Cardiologia','Cirurgia cardiovascular','Cirurgia da mão','Cirurgia de cabeça e pescoço','Cirurgia do aparelho digestivo','Cirurgia geral','Cirurgia oncológica','Cirurgia pediátrica','Cirurgia plástica','Cirurgia torácica','Cirurgia vascular','Clínica médica','Coloproctologia','Dermatologia','Endocrinologia e metabologia','Endoscopia','Gastroenterologia','Genética médica','Geriatria','Ginecologia e obstetrícia','Hematologia e hemoterapia','Homeopatia','Infectologia','Mastologia','Medicina de emergência','Medicina de família e comunidade','Medicina do trabalho','Medicina do tráfego','Medicina esportiva','Medicina física e reabilitação','Medicina intensiva','Medicina legal e perícia médica','Medicina nuclear','Medicina preventiva e social','Nefrologia','Neurocirurgia','Neurologia','Nutrologia','Oftalmologia','Oncologia clínica','Ortopedia e traumatologia','Otorrinolaringologia','Patologia','Patologia clínica/medicina laboratorial','Pediatria','Pneumologia','Psiquiatria','Radiologia e diagnóstico por imagem','Radioterapia','Reumatologia','Urologia']; const savedSpecialtyDetails = Array.isArray(profile.specialtyDetails) ? profile.specialtyDetails : []; let selectedSpecialties = [...new Set((profile.specialties || []).map((item) => item === 'Ortopedia' ? 'Ortopedia e traumatologia' : item))].map((name) => ({ name, doctor: '', clinic: '', contact: '', ...(savedSpecialtyDetails.find((item) => item.name === name) || {}) })); Object.entries(profile).forEach(([key, value]) => { if (['specialties','specialtyDetails','photo','allergies','emergency'].includes(key)) return; const field = $(`[name="${key}"]`); if (field) field.value = value; });
$('.specialties').insertAdjacentHTML('afterend', `<fieldset class="wide health-plan-card"><legend>Carteirinha do plano de saúde</legend><p>Inclua imagens legíveis da frente e do verso da carteirinha.</p><div class="health-plan-card-grid"><article><strong>Frente</strong><div id="plan-card-front-preview" class="plan-card-preview" hidden><img alt="Frente da carteirinha do plano de saúde" /></div><label class="secondary-button plan-card-upload">Selecionar frente<input id="plan-card-front" type="file" accept="image/*" /></label><button class="text-button" id="remove-plan-card-front" type="button" hidden>Remover</button></article><article><strong>Verso</strong><div id="plan-card-back-preview" class="plan-card-preview" hidden><img alt="Verso da carteirinha do plano de saúde" /></div><label class="secondary-button plan-card-upload">Selecionar verso<input id="plan-card-back" type="file" accept="image/*" /></label><button class="text-button" id="remove-plan-card-back" type="button" hidden>Remover</button></article></div></fieldset>`);
let planCardFront = profile.planCardFront || '';
let planCardBack = profile.planCardBack || '';
let profilePhotoX = Number(profile.photoPositionX ?? 50);
let profilePhotoY = Number(profile.photoPositionY ?? 25);
function calculateAge(birthDate) { if (!birthDate) return null; const [year, month, day] = birthDate.split('-').map(Number); const today = new Date(); let age = today.getFullYear() - year; if (today.getMonth() + 1 < month || (today.getMonth() + 1 === month && today.getDate() < day)) age -= 1; return age >= 0 ? age : null; }
function renderAge(data = storage.get('vitalink-profile', {})) { const age = calculateAge(data.birthDate); $('#calculated-age').textContent = age === null ? 'Não informada' : `${age} anos`; }
function getInitials(name = '') { const words = name.trim().split(/\s+/).filter(Boolean); return words.length ? `${words[0][0]}${words.length > 1 ? words.at(-1)[0] : ''}`.toUpperCase() : 'VL'; }
function renderIdentity(data = storage.get('vitalink-profile', {})) { const name = (data.name || '').trim(); $('#welcome-name').textContent = name ? name.split(/\s+/)[0] : 'Usuário'; const initials = $('#profile-initials'); initials.textContent = getInitials(name); initials.hidden = Boolean(data.photo); const x = Number(data.photoPositionX ?? profilePhotoX ?? 50); const y = Number(data.photoPositionY ?? profilePhotoY ?? 25); const position = `${x}% ${y}%`; const avatar = $('#profile-avatar'); avatar.hidden = !data.photo; if (data.photo) { avatar.src = data.photo; avatar.style.objectPosition = position; } const frame = $('#profile-photo-frame'); frame.hidden = !data.photo; const preview = $('#profile-photo-preview'); if (data.photo) { preview.src = data.photo; preview.style.objectPosition = position; } const controls = $('#photo-position-controls'); controls.hidden = !data.photo; $('#photo-position-x').value = x; $('#photo-position-y').value = y; }
function renderPlanCards() { [['front', planCardFront], ['back', planCardBack]].forEach(([side, data]) => { const preview = $(`#plan-card-${side}-preview`); preview.hidden = !data; if (data) preview.querySelector('img').src = data; $(`#remove-plan-card-${side}`).hidden = !data; }); }
function compressCardImage(file) { return new Promise((resolve, reject) => { const image = new Image(); const url = URL.createObjectURL(file); image.addEventListener('load', () => { const scale = Math.min(1, 1400 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(url); resolve(canvas.toDataURL('image/jpeg', 0.78)); }); image.addEventListener('error', () => { URL.revokeObjectURL(url); reject(new Error('Imagem inválida')); }); image.src = url; }); }
async function selectPlanCard(side, file) { if (!file) return; if (file.size > 8 * 1024 * 1024) { toast('Escolha uma imagem de até 8 MB.'); return; } try { const data = await compressCardImage(file); if (side === 'front') planCardFront = data; else planCardBack = data; renderPlanCards(); toast(`${side === 'front' ? 'Frente' : 'Verso'} da carteirinha adicionada.`); } catch (error) { toast('Não foi possível carregar a imagem da carteirinha.'); } }
$('#plan-card-front').addEventListener('change', (event) => { selectPlanCard('front', event.target.files[0]); event.target.value = ''; });
$('#plan-card-back').addEventListener('change', (event) => { selectPlanCard('back', event.target.files[0]); event.target.value = ''; });
$('#remove-plan-card-front').addEventListener('click', () => { planCardFront = ''; renderPlanCards(); });
$('#remove-plan-card-back').addEventListener('click', () => { planCardBack = ''; renderPlanCards(); });
renderPlanCards();
function renderSpecialtySelection() { $('#selected-specialties').innerHTML = selectedSpecialties.length ? selectedSpecialties.map((item) => `<article class="specialty-professional" data-specialty-card="${escapeHtml(item.name)}"><div class="specialty-professional-heading"><strong>${escapeHtml(item.name)}</strong><button type="button" data-remove-specialty="${escapeHtml(item.name)}" aria-label="Remover ${escapeHtml(item.name)}">×</button></div><div class="specialty-professional-fields"><label>Nome do médico<input value="${escapeHtml(item.doctor || '')}" data-specialty-field="doctor" placeholder="Ex.: Dra. Ana Silva" /></label><label>Clínica / local de atendimento<input value="${escapeHtml(item.clinic || '')}" data-specialty-field="clinic" placeholder="Ex.: Clínica Vita" /></label><label class="wide">Contato<input value="${escapeHtml(item.contact || '')}" data-specialty-field="contact" placeholder="Telefone, WhatsApp ou e-mail" /></label></div></article>`).join('') : '<span class="specialty-empty">Nenhuma especialidade selecionada.</span>'; }
function getSelectedSpecialties() { return selectedSpecialties.map((item) => item.name); }
$('.specialties').innerHTML = `<legend>Especialidades médicas</legend><p>Selecione as especialidades que acompanham o paciente e informe os dados de contato.</p><div class="specialty-picker"><select id="specialty-select" aria-label="Escolher especialidade médica"><option value="">Selecione uma especialidade</option>${CFM_SPECIALTIES.map((item) => `<option value="${item}">${item}</option>`).join('')}</select><button id="add-specialty" class="secondary-button" type="button">Adicionar</button></div><div id="selected-specialties" class="selected-specialties" aria-live="polite"></div>`;
renderSpecialtySelection();
$('#add-specialty').addEventListener('click', () => { const value = $('#specialty-select').value; if (!value || selectedSpecialties.some((item) => item.name === value)) return; selectedSpecialties.unshift({ name: value, doctor: '', clinic: '', contact: '' }); $('#specialty-select').value = ''; renderSpecialtySelection(); $('#selected-specialties input')?.focus(); renderBodyMap({ ...storage.get('vitalink-profile', {}), gender: $('#profile-form [name="gender"]').value, specialties: getSelectedSpecialties() }); });
$('#selected-specialties').addEventListener('click', (event) => { const button = event.target.closest('[data-remove-specialty]'); if (!button) return; selectedSpecialties = selectedSpecialties.filter((item) => item.name !== button.dataset.removeSpecialty); renderSpecialtySelection(); renderBodyMap({ ...storage.get('vitalink-profile', {}), gender: $('#profile-form [name="gender"]').value, specialties: getSelectedSpecialties() }); });
$('#selected-specialties').addEventListener('input', (event) => { const input = event.target.closest('[data-specialty-field]'); const card = event.target.closest('[data-specialty-card]'); if (!input || !card) return; const item = selectedSpecialties.find((specialty) => specialty.name === card.dataset.specialtyCard); if (item) item[input.dataset.specialtyField] = input.value; });
const BODY_AREAS = [
  { match: /neurolog|neurocirurg|psiquiatr/, className: 'head', icon: '●', label: 'cabeça e sistema nervoso' },
  { match: /oftalm|otorrino|cabeça e pescoço/, className: 'face', icon: '●', label: 'cabeça e sentidos' },
  { match: /cardi|cirurgia cardiovascular|angiologia|vascular/, className: 'heart', icon: '♥', label: 'coração e circulação' },
  { match: /pneum|torácica/, className: 'lungs', icon: '●', label: 'pulmões e tórax' },
  { match: /gastro|digestivo|coloprocto|endoscopia|hepat/, className: 'abdomen', icon: '●', label: 'abdômen e aparelho digestivo' },
  { match: /uro|nefrolog|ginecologia/, className: 'pelvis', icon: '●', label: 'rins e região pélvica' },
  { match: /ortopedia|reumatologia|física e reabilitação|esportiva/, className: 'joints', icon: '✦', label: 'ossos, músculos e articulações' }
];
function getBodyArea(specialty) { const normalized = specialty.toLocaleLowerCase('pt-BR'); return BODY_AREAS.find((area) => area.match.test(normalized)); }
function renderBodyMap(data = storage.get('vitalink-profile', {})) { const male = data.gender === 'Masculino'; const image = $('#patient-body'); image.src = `${encodeURI(male ? 'Sexo Masculino.png' : 'Sexo Feminino.png')}?mapa=3`; image.alt = male ? 'Mapa frontal do corpo masculino' : 'Mapa frontal do corpo feminino'; $('#map-caption').textContent = `Mapa ${male ? 'masculino' : 'feminino'} · vista frontal`; const specialties = Array.isArray(data.specialties) ? data.specialties.map((item) => item === 'Ortopedia' ? 'Ortopedia e traumatologia' : item) : []; const mapped = specialties.map((name) => ({ name, area: getBodyArea(name) })); $('#body-markers').innerHTML = mapped.filter((item) => item.area).map((item, index) => `<button class="body-marker ${item.area.className} offset-${index % 3}" type="button" data-area="${escapeHtml(item.name)}" title="${escapeHtml(item.name)} — ${item.area.label}">${item.area.icon}</button>`).join(''); $('#body-specialty-list').innerHTML = mapped.length ? mapped.map((item) => `<button type="button" data-area="${escapeHtml(item.name)}">${item.area ? item.area.icon : '○'} ${escapeHtml(item.name)}${item.area ? '' : ' · acompanhamento geral'}</button>`).join('') : '<span class="specialty-empty">Nenhuma especialidade cadastrada no perfil.</span>'; const anatomical = mapped.filter((item) => item.area).length; $('#body-feedback').textContent = anatomical ? `${anatomical} especialidade(s) com correspondência anatômica destacada(s).` : specialties.length ? 'As especialidades cadastradas são de acompanhamento geral e não correspondem a um ponto anatômico específico.' : 'Inclua especialidades na Ficha do Paciente para atualizar o mapa.'; }
$('#choose-photo').addEventListener('click', () => $('#profile-photo').click());
$('#profile-photo').addEventListener('change', (event) => { const [file] = event.target.files; if (!file) return; if (file.size > 2 * 1024 * 1024) { event.target.value = ''; toast('Escolha uma foto de até 2 MB.'); return; } const reader = new FileReader(); reader.addEventListener('load', () => { profilePhoto = reader.result; profilePhotoX = 50; profilePhotoY = 25; renderIdentity({ ...storage.get('vitalink-profile', {}), photo: profilePhoto, photoPositionX: profilePhotoX, photoPositionY: profilePhotoY, name: $('#profile-form [name="name"]').value }); }); reader.readAsDataURL(file); });
function previewPhotoPosition() { profilePhotoX = Number($('#photo-position-x').value); profilePhotoY = Number($('#photo-position-y').value); renderIdentity({ ...storage.get('vitalink-profile', {}), photo: profilePhoto, photoPositionX: profilePhotoX, photoPositionY: profilePhotoY, name: $('#profile-form [name="name"]').value }); }
$('#photo-position-x').addEventListener('input', previewPhotoPosition);
$('#photo-position-y').addEventListener('input', previewPhotoPosition);
$('#profile-form [name="birthDate"]').max = new Date().toISOString().slice(0, 10);
$('#profile-form [name="birthDate"]').addEventListener('change', (event) => renderAge({ birthDate: event.target.value }));
$('#profile-form').addEventListener('submit', (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); delete data['profile-photo']; data.specialties = getSelectedSpecialties(); data.specialtyDetails = selectedSpecialties.map((item) => ({ ...item })); data.photo = profilePhoto; data.photoPositionX = profilePhotoX; data.photoPositionY = profilePhotoY; data.planCardFront = planCardFront; data.planCardBack = planCardBack; data.age = calculateAge(data.birthDate); data.updatedAt = new Date().toISOString(); storage.set('vitalink-profile', data); renderIdentity(data); renderAge(data); renderBodyMap(data); renderPlanCards(); renderTimeline(); toast('Perfil e mapa corporal atualizados.'); });
$('#profile-form [name="gender"]').addEventListener('change', (event) => { const preview = { ...storage.get('vitalink-profile', {}), gender: event.target.value, specialties: getSelectedSpecialties() }; renderBodyMap(preview); });
document.querySelectorAll('#profile-form [name="specialties"]').forEach((field) => field.addEventListener('change', () => { const preview = { ...storage.get('vitalink-profile', {}), gender: $('#profile-form [name="gender"]').value, specialties: getSelectedSpecialties() }; renderBodyMap(preview); }));
document.addEventListener('click', (event) => { const button = event.target.closest('[data-area]'); if (!button) return; $('#body-feedback').textContent = `${button.dataset.area} selecionada conforme a especialidade cadastrada no perfil.`; });

$('#quick-event-form').addEventListener('submit', (event) => { event.preventDefault(); const description = $('#quick-event-description').value.trim(); if (!description) return; const now = new Date(); const records = storage.get('vitalink-health-events', []); records.push({ id: Date.now(), createdAt: now.toISOString(), updatedAt: now.toISOString(), date: todayKey(), type: 'Monitoramento diário', description, doctor: '', diagnosis: '', exams: '', documents: [] }); storage.set('vitalink-health-events', records); event.target.reset(); renderHealthEvents(); renderTimeline(); toast('Monitoramento registrado em Eventos.'); });

$('#health-event-date').value = todayKey();
renderAppointments(); renderMedicines(); renderFiles(); renderHealthEvents(); renderIdentity(profile); renderAge(profile); renderBodyMap(); renderTimeline();
setTimeout(() => $('#splash-screen').style.opacity = '0', 900);
setTimeout(() => $('#splash-screen').style.display = 'none', 1350);
