-- VitaLink Onda 1 — multi-perfil + RBAC endurecido (idempotente)

-- Perfil Paciente (uso pessoal)
INSERT INTO perfis (id, nome, descricao) VALUES
  (6, 'Paciente', 'Acesso à própria saúde e módulo Início')
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome,
  descricao = EXCLUDED.descricao;

SELECT setval(pg_get_serial_sequence('perfis', 'id'), GREATEST((SELECT MAX(id) FROM perfis), 6));

CREATE TABLE IF NOT EXISTS usuario_perfis (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE CASCADE,
  perfil_id INTEGER NOT NULL REFERENCES perfis (id) ON UPDATE CASCADE ON DELETE CASCADE,
  paciente_id INTEGER NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE SET NULL,
  rotulo VARCHAR(120) NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_usuario_perfil_escopo
  ON usuario_perfis (usuario_id, perfil_id, COALESCE(paciente_id, 0));

CREATE INDEX IF NOT EXISTS idx_usuario_perfis_usuario ON usuario_perfis (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_perfis_perfil ON usuario_perfis (perfil_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_usuario_perfis_updated_at'
  ) THEN
    CREATE TRIGGER trg_usuario_perfis_updated_at
      BEFORE UPDATE ON usuario_perfis
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
  END IF;
END $$;

-- Migra perfil legado → usuario_perfis (default)
INSERT INTO usuario_perfis (usuario_id, perfil_id, paciente_id, rotulo, ativo, is_default)
SELECT u.id, u.perfil_id, NULL, p.nome, TRUE, TRUE
FROM usuarios u
INNER JOIN perfis p ON p.id = u.perfil_id
WHERE NOT EXISTS (
  SELECT 1 FROM usuario_perfis up
  WHERE up.usuario_id = u.id AND up.perfil_id = u.perfil_id AND up.paciente_id IS NULL
);

-- Admin de exemplo também como Paciente (uso pessoal / Profile Switch)
INSERT INTO usuario_perfis (usuario_id, perfil_id, paciente_id, rotulo, ativo, is_default)
SELECT 1, 6, NULL, 'Paciente (uso pessoal)', TRUE, FALSE
WHERE EXISTS (SELECT 1 FROM usuarios WHERE id = 1)
  AND NOT EXISTS (
    SELECT 1 FROM usuario_perfis
    WHERE usuario_id = 1 AND perfil_id = 6 AND paciente_id IS NULL
  );

-- Permissões Paciente (perfil 6): Dashboard + Início
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 6, m.id, TRUE,
       CASE WHEN m.rota = '/inicio' THEN TRUE ELSE FALSE END,
       CASE WHEN m.rota = '/inicio' THEN TRUE ELSE FALSE END,
       CASE WHEN m.rota = '/inicio' THEN TRUE ELSE FALSE END
FROM menus m
WHERE m.id IN (1, 2)
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = EXCLUDED.pode_ler,
  pode_criar = EXCLUDED.pode_criar,
  pode_editar = EXCLUDED.pode_editar,
  pode_deletar = EXCLUDED.pode_deletar;

-- Cuidador: pacientes só leitura (sem criar/editar/deletar)
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 4, 31, TRUE, FALSE, FALSE, FALSE
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = TRUE,
  pode_criar = FALSE,
  pode_editar = FALSE,
  pode_deletar = FALSE;

-- Responsável: responsáveis só leitura; pacientes só leitura
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 5, 37, TRUE, FALSE, FALSE, FALSE
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = TRUE,
  pode_criar = FALSE,
  pode_editar = FALSE,
  pode_deletar = FALSE;

INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 5, 31, TRUE, FALSE, FALSE, FALSE
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = TRUE,
  pode_criar = FALSE,
  pode_editar = FALSE,
  pode_deletar = FALSE;

-- Garantir menu pai Saúde para quem ganhou filhos
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 5, 30, TRUE, FALSE, FALSE, FALSE
ON CONFLICT (perfil_id, menu_id) DO NOTHING;

INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 4, 30, TRUE, FALSE, FALSE, FALSE
ON CONFLICT (perfil_id, menu_id) DO NOTHING;
