-- VitaLink — catálogo de medicamentos (50+) e APIs do Paciente/Autocuidado
-- Idempotente. O menu lateral de Paciente/Autocuidado continua filtrado no backend
-- (apenas Dashboard e Início); as permissões abaixo liberam as APIs da própria saúde.

CREATE TABLE IF NOT EXISTS catalogo_medicamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_comercial VARCHAR(180) NOT NULL,
  principio_ativo VARCHAR(180) NOT NULL,
  dosagem VARCHAR(80) NOT NULL,
  forma_farmaceutica VARCHAR(80) NOT NULL DEFAULT 'comprimido',
  classe_terapeutica VARCHAR(120) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT catalogo_medicamentos_uniq UNIQUE (nome_comercial, dosagem, forma_farmaceutica)
);

CREATE INDEX IF NOT EXISTS idx_catalogo_med_nome ON catalogo_medicamentos (nome_comercial);
CREATE INDEX IF NOT EXISTS idx_catalogo_med_pa ON catalogo_medicamentos (principio_ativo);
CREATE INDEX IF NOT EXISTS idx_catalogo_med_busca ON catalogo_medicamentos (nome_comercial, principio_ativo);

-- Paciente (6) e Autocuidado (7): leitura/escrita da própria saúde via Início.
-- Não reduz permissões já existentes (OR).
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT p.id, m.id, TRUE,
  CASE WHEN m.rota IN (
    '/inicio', '/remedios', '/exames-receitas', '/agenda', '/consultas', '/rotina'
  ) THEN TRUE ELSE FALSE END,
  CASE WHEN m.rota IN (
    '/inicio', '/remedios', '/pacientes', '/exames-receitas',
    '/agenda', '/consultas', '/rotina'
  ) THEN TRUE ELSE FALSE END,
  CASE WHEN m.rota IN ('/inicio', '/remedios', '/consultas', '/rotina') THEN TRUE ELSE FALSE END
FROM perfis p
CROSS JOIN menus m
WHERE p.id IN (6, 7)
  AND m.id IN (1, 2, 30, 31, 32, 33, 34, 35, 38, 40, 50, 51, 52, 53, 54)
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = TRUE,
  pode_criar = permissoes_acesso.pode_criar OR EXCLUDED.pode_criar,
  pode_editar = permissoes_acesso.pode_editar OR EXCLUDED.pode_editar,
  pode_deletar = permissoes_acesso.pode_deletar OR EXCLUDED.pode_deletar;
