-- VitaLink Onda 0 — idempotente (PostgreSQL)
-- arquivos, hospitais opcionais, whatsapp, pacientes sem diagnóstico obrigatório, carteirinha

-- -----------------------------------------------------------------------------
-- Arquivos (upload)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS arquivos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  nome_original VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  tamanho_bytes INTEGER NOT NULL DEFAULT 0,
  caminho VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_arquivos_usuario ON arquivos (usuario_id);

-- -----------------------------------------------------------------------------
-- Hospitais / Farmácias: CNPJ e Razão Social opcionais + WhatsApp
-- -----------------------------------------------------------------------------
ALTER TABLE hospitais_clinicas ALTER COLUMN razao_social DROP NOT NULL;
ALTER TABLE hospitais_clinicas ALTER COLUMN documento DROP NOT NULL;
ALTER TABLE farmacias ALTER COLUMN razao_social DROP NOT NULL;
ALTER TABLE farmacias ALTER COLUMN documento DROP NOT NULL;

ALTER TABLE hospitais_clinicas ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(30) NULL;
ALTER TABLE farmacias ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(30) NULL;

-- Migra telefone_secundario → whatsapp quando whatsapp vazio
UPDATE hospitais_clinicas
SET whatsapp = telefone_secundario
WHERE (whatsapp IS NULL OR whatsapp = '')
  AND telefone_secundario IS NOT NULL
  AND telefone_secundario <> '';

UPDATE farmacias
SET whatsapp = telefone_secundario
WHERE (whatsapp IS NULL OR whatsapp = '')
  AND telefone_secundario IS NOT NULL
  AND telefone_secundario <> '';

-- Índice único parcial (permite vários NULL em documento)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk_hospitais_documento'
  ) THEN
    ALTER TABLE hospitais_clinicas DROP CONSTRAINT uk_hospitais_documento;
  END IF;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk_farmacias_documento'
  ) THEN
    ALTER TABLE farmacias DROP CONSTRAINT uk_farmacias_documento;
  END IF;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_hospitais_documento_notnull
  ON hospitais_clinicas (documento) WHERE documento IS NOT NULL AND documento <> '';
CREATE UNIQUE INDEX IF NOT EXISTS uk_farmacias_documento_notnull
  ON farmacias (documento) WHERE documento IS NOT NULL AND documento <> '';

-- -----------------------------------------------------------------------------
-- Pacientes: remover diagnóstico obrigatório + carteirinha arquivos
-- -----------------------------------------------------------------------------
ALTER TABLE pacientes ALTER COLUMN diagnostico_principal DROP NOT NULL;

ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS foto_arquivo_id INTEGER NULL
  REFERENCES arquivos (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS convenio_frente_arquivo_id INTEGER NULL
  REFERENCES arquivos (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS convenio_verso_arquivo_id INTEGER NULL
  REFERENCES arquivos (id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Comentário de rastreabilidade
COMMENT ON TABLE arquivos IS 'Metadados de upload (foto, carteirinha, documentos)';
COMMENT ON COLUMN auditoria_logs.metadados_json IS 'JSON sanitizado; pode incluir diff {antes,depois} sem dados clínicos';
