-- VitaLink — Módulo Início (PostgreSQL)
-- Idempotente: pode rodar em bancos já existentes

CREATE TABLE IF NOT EXISTS inicio_registros (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  paciente_id INTEGER NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE SET NULL,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'saude'
    CHECK (tipo IN ('saude', 'aviso', 'compromisso', 'medicamento', 'outro')),
  data_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  prioridade TEXT NOT NULL DEFAULT 'media'
    CHECK (prioridade IN ('baixa', 'media', 'alta')),
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'arquivado')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inicio_data ON inicio_registros (data_registro DESC);
CREATE INDEX IF NOT EXISTS idx_inicio_tipo ON inicio_registros (tipo);
CREATE INDEX IF NOT EXISTS idx_inicio_status ON inicio_registros (status);
CREATE INDEX IF NOT EXISTS idx_inicio_usuario ON inicio_registros (usuario_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_inicio_registros_updated_at'
  ) THEN
    CREATE TRIGGER trg_inicio_registros_updated_at
      BEFORE UPDATE ON inicio_registros
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
  END IF;
END $$;

-- Menu Início (após Dashboard, ordem 15)
INSERT INTO menus (id, titulo, rota, icone, ordem, menu_pai_id, ativo)
VALUES (2, 'Início', '/inicio', 'home', 15, NULL, TRUE)
ON CONFLICT (id) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  rota = EXCLUDED.rota,
  icone = EXCLUDED.icone,
  ordem = EXCLUDED.ordem,
  menu_pai_id = EXCLUDED.menu_pai_id,
  ativo = TRUE;

SELECT setval(pg_get_serial_sequence('menus', 'id'), GREATEST((SELECT MAX(id) FROM menus), 2));

-- Permissões: perfis operacionais ganham CRUD no Início
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT p.id, 2, TRUE, TRUE, TRUE, TRUE
FROM perfis p
WHERE p.id = 1
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = TRUE,
  pode_criar = TRUE,
  pode_editar = TRUE,
  pode_deletar = TRUE;

INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT p.id, 2, TRUE, TRUE, TRUE, TRUE
FROM perfis p
WHERE p.id IN (2, 3, 4, 5)
ON CONFLICT (perfil_id, menu_id) DO UPDATE SET
  pode_ler = TRUE,
  pode_criar = TRUE,
  pode_editar = TRUE,
  pode_deletar = TRUE;
