-- =============================================================================
-- VitaLink — Schema PostgreSQL (consolidado)
-- Encoding: UTF8 | Schema: public
-- Senha admin seed: Admin@Vitalink1
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- RBAC
-- -----------------------------------------------------------------------------

CREATE TABLE perfis (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  descricao VARCHAR(255) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_perfis_nome UNIQUE (nome)
);

CREATE TABLE menus (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  rota VARCHAR(180) NULL,
  icone VARCHAR(80) NULL,
  ordem INTEGER NOT NULL DEFAULT 0,
  menu_pai_id INTEGER NULL REFERENCES menus (id) ON UPDATE CASCADE ON DELETE SET NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_menus_pai ON menus (menu_pai_id);
CREATE INDEX idx_menus_ordem ON menus (ordem);

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(180) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo', 'bloqueado')),
  perfil_id INTEGER NOT NULL REFERENCES perfis (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_usuarios_email UNIQUE (email)
);
CREATE INDEX idx_usuarios_perfil ON usuarios (perfil_id);
CREATE INDEX idx_usuarios_status ON usuarios (status);

CREATE TABLE permissoes_acesso (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id INTEGER NOT NULL REFERENCES perfis (id) ON UPDATE CASCADE ON DELETE CASCADE,
  menu_id INTEGER NOT NULL REFERENCES menus (id) ON UPDATE CASCADE ON DELETE CASCADE,
  pode_ler BOOLEAN NOT NULL DEFAULT FALSE,
  pode_criar BOOLEAN NOT NULL DEFAULT FALSE,
  pode_editar BOOLEAN NOT NULL DEFAULT FALSE,
  pode_deletar BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_permissoes_perfil_menu UNIQUE (perfil_id, menu_id)
);
CREATE INDEX idx_permissoes_menu ON permissoes_acesso (menu_id);

-- -----------------------------------------------------------------------------
-- Saúde
-- -----------------------------------------------------------------------------

CREATE TABLE hospitais_clinicas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social VARCHAR(180) NOT NULL,
  nome_fantasia VARCHAR(180) NOT NULL,
  tipo_documento TEXT NOT NULL DEFAULT 'cnpj'
    CHECK (tipo_documento IN ('cnpj', 'cpf')),
  documento VARCHAR(18) NOT NULL,
  telefone_principal VARCHAR(30) NOT NULL,
  telefone_secundario VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  cep CHAR(8) NOT NULL,
  logradouro VARCHAR(180) NOT NULL,
  numero VARCHAR(20) NOT NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(120) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf CHAR(2) NOT NULL,
  observacoes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_hospitais_documento UNIQUE (documento)
);
CREATE INDEX idx_hospitais_nome ON hospitais_clinicas (nome_fantasia);
CREATE INDEX idx_hospitais_status ON hospitais_clinicas (status);

CREATE TABLE farmacias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social VARCHAR(180) NOT NULL,
  nome_fantasia VARCHAR(180) NOT NULL,
  tipo_documento TEXT NOT NULL DEFAULT 'cnpj'
    CHECK (tipo_documento IN ('cnpj', 'cpf')),
  documento VARCHAR(18) NOT NULL,
  telefone_principal VARCHAR(30) NOT NULL,
  telefone_secundario VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  cep CHAR(8) NOT NULL,
  logradouro VARCHAR(180) NOT NULL,
  numero VARCHAR(20) NOT NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(120) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf CHAR(2) NOT NULL,
  observacoes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_farmacias_documento UNIQUE (documento)
);
CREATE INDEX idx_farmacias_nome ON farmacias (nome_fantasia);
CREATE INDEX idx_farmacias_status ON farmacias (status);

CREATE TABLE cuidadores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  nome VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  telefone_principal VARCHAR(30) NOT NULL,
  telefone_secundario VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  foto_url TEXT NULL,
  turno VARCHAR(80) NULL,
  especialidade VARCHAR(120) NULL,
  cep CHAR(8) NOT NULL,
  logradouro VARCHAR(180) NOT NULL,
  numero VARCHAR(20) NOT NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(120) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf CHAR(2) NOT NULL,
  observacoes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cuidadores_usuario UNIQUE (usuario_id),
  CONSTRAINT uk_cuidadores_cpf UNIQUE (cpf)
);
CREATE INDEX idx_cuidadores_status ON cuidadores (status);

CREATE TABLE responsaveis (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  nome VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  telefone_principal VARCHAR(30) NOT NULL,
  telefone_secundario VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  foto_url TEXT NULL,
  grau_parentesco VARCHAR(80) NULL,
  cep CHAR(8) NOT NULL,
  logradouro VARCHAR(180) NOT NULL,
  numero VARCHAR(20) NOT NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(120) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  uf CHAR(2) NOT NULL,
  observacoes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_responsaveis_usuario UNIQUE (usuario_id),
  CONSTRAINT uk_responsaveis_cpf UNIQUE (cpf)
);
CREATE INDEX idx_responsaveis_status ON responsaveis (status);

CREATE TABLE medicos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  hospital_clinica_id INTEGER NOT NULL REFERENCES hospitais_clinicas (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  nome VARCHAR(150) NOT NULL,
  crm VARCHAR(20) NOT NULL,
  uf_crm CHAR(2) NOT NULL,
  especialidade VARCHAR(120) NULL,
  telefone_principal VARCHAR(30) NOT NULL,
  telefone_secundario VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  cep CHAR(8) NULL,
  logradouro VARCHAR(180) NULL,
  numero VARCHAR(20) NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(120) NULL,
  cidade VARCHAR(120) NULL,
  uf CHAR(2) NULL,
  observacoes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_medicos_crm_uf UNIQUE (crm, uf_crm)
);
CREATE INDEX idx_medicos_usuario ON medicos (usuario_id);
CREATE INDEX idx_medicos_hospital ON medicos (hospital_clinica_id);
CREATE INDEX idx_medicos_status ON medicos (status);

CREATE TABLE pacientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  data_nascimento DATE NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  diagnostico_principal VARCHAR(255) NOT NULL,
  alergias TEXT NULL,
  tipo_sanguineo TEXT NOT NULL DEFAULT 'NI'
    CHECK (tipo_sanguineo IN ('A+','A-','B+','B-','AB+','AB-','O+','O-','NI')),
  foto_url TEXT NULL,
  telefone_principal VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  convenio_nome VARCHAR(120) NULL,
  convenio_numero VARCHAR(60) NULL,
  convenio_validade DATE NULL,
  responsavel_id INTEGER NULL REFERENCES responsaveis (id) ON UPDATE CASCADE ON DELETE SET NULL,
  cuidador_id INTEGER NULL REFERENCES cuidadores (id) ON UPDATE CASCADE ON DELETE SET NULL,
  medico_id INTEGER NULL REFERENCES medicos (id) ON UPDATE CASCADE ON DELETE SET NULL,
  cep CHAR(8) NULL,
  logradouro VARCHAR(180) NULL,
  numero VARCHAR(20) NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(120) NULL,
  cidade VARCHAR(120) NULL,
  uf CHAR(2) NULL,
  observacoes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_pacientes_cpf UNIQUE (cpf)
);
CREATE INDEX idx_pacientes_status ON pacientes (status);
CREATE INDEX idx_pacientes_responsavel ON pacientes (responsavel_id);
CREATE INDEX idx_pacientes_cuidador ON pacientes (cuidador_id);
CREATE INDEX idx_pacientes_medico ON pacientes (medico_id);

CREATE TABLE remedios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_comercial VARCHAR(180) NOT NULL,
  principio_ativo VARCHAR(180) NOT NULL,
  concentracao VARCHAR(80) NULL,
  forma_farmaceutica TEXT NOT NULL DEFAULT 'comprimido'
    CHECK (forma_farmaceutica IN (
      'comprimido','capsula','xarope','solucao','injecao',
      'pomada','creme','gotas','inalador','outro'
    )),
  registro_anvisa VARCHAR(40) NULL,
  instrucoes_uso TEXT NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_remedios_nome ON remedios (nome_comercial);
CREATE INDEX idx_remedios_principio ON remedios (principio_ativo);
CREATE INDEX idx_remedios_anvisa ON remedios (registro_anvisa);

-- -----------------------------------------------------------------------------
-- Atividades / Anamnese
-- -----------------------------------------------------------------------------

CREATE TABLE paciente_anamnese (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  doencas_preexistentes TEXT NULL,
  historico_familiar TEXT NULL,
  cirurgias_anteriores TEXT NULL,
  sono TEXT NULL,
  alimentacao TEXT NULL,
  mobilidade TEXT NULL,
  autonomia TEXT NULL,
  medicamentos_contraindicados TEXT NULL,
  alergias_alimentares TEXT NULL,
  limitacoes_fisicas_cognitivas TEXT NULL,
  instrucoes_cuidadores TEXT NULL,
  episodios_confusao TEXT NULL,
  contato_emergencia_nome VARCHAR(150) NULL,
  contato_emergencia_telefone VARCHAR(30) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_anamnese_paciente UNIQUE (paciente_id)
);

CREATE TABLE consultas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  medico_id INTEGER NULL REFERENCES medicos (id) ON UPDATE CASCADE ON DELETE SET NULL,
  profissional_nome VARCHAR(150) NOT NULL,
  especialidade VARCHAR(120) NOT NULL,
  local_tipo TEXT NOT NULL DEFAULT 'clinica'
    CHECK (local_tipo IN ('clinica','hospital','domiciliar','outro')),
  hospital_clinica_id INTEGER NULL REFERENCES hospitais_clinicas (id) ON UPDATE CASCADE ON DELETE SET NULL,
  local_descricao VARCHAR(255) NULL,
  data_hora TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente','concluido','atrasado','cancelado')),
  lembrete_minutos INTEGER NULL DEFAULT 60,
  anotacoes_pos TEXT NULL,
  observacoes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_consultas_paciente ON consultas (paciente_id);
CREATE INDEX idx_consultas_data ON consultas (data_hora);
CREATE INDEX idx_consultas_status ON consultas (status);

CREATE TABLE atendimentos_rotina (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'medicamento'
    CHECK (tipo IN ('medicamento','pressao','glicemia','banho','curativo','outro')),
  remedio_id INTEGER NULL REFERENCES remedios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT NULL,
  horario TIME NOT NULL,
  dias_semana VARCHAR(20) NOT NULL DEFAULT '1,2,3,4,5,6,7',
  data_inicio DATE NOT NULL,
  data_fim DATE NULL,
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo','inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_rotina_paciente ON atendimentos_rotina (paciente_id);
CREATE INDEX idx_rotina_status ON atendimentos_rotina (status);

CREATE TABLE atendimento_execucoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atendimento_rotina_id INTEGER NOT NULL REFERENCES atendimentos_rotina (id) ON UPDATE CASCADE ON DELETE CASCADE,
  paciente_id INTEGER NOT NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  data_hora_prevista TIMESTAMPTZ NOT NULL,
  data_hora_realizada TIMESTAMPTZ NULL,
  status TEXT NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente','concluido','atrasado','nao_realizado','cancelado')),
  motivo_nao_realizacao VARCHAR(255) NULL,
  executado_por INTEGER NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_execucao_rotina_prevista UNIQUE (atendimento_rotina_id, data_hora_prevista)
);
CREATE INDEX idx_execucao_paciente_data ON atendimento_execucoes (paciente_id, data_hora_prevista);
CREATE INDEX idx_execucao_status ON atendimento_execucoes (status);

CREATE TABLE agenda_eventos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER NOT NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'outro'
    CHECK (tipo IN ('consulta','medicamento','cuidado','sessao','outro')),
  origem_tabela VARCHAR(40) NOT NULL,
  origem_id INTEGER NOT NULL,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT NULL,
  data_hora_inicio TIMESTAMPTZ NOT NULL,
  data_hora_fim TIMESTAMPTZ NULL,
  status TEXT NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente','concluido','atrasado','cancelado','nao_realizado')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agenda_origem UNIQUE (origem_tabela, origem_id)
);
CREATE INDEX idx_agenda_paciente_data ON agenda_eventos (paciente_id, data_hora_inicio);
CREATE INDEX idx_agenda_status ON agenda_eventos (status);
CREATE INDEX idx_agenda_tipo ON agenda_eventos (tipo);

-- -----------------------------------------------------------------------------
-- Página Início (registros / destaques / avisos)
-- -----------------------------------------------------------------------------

CREATE TABLE inicio_registros (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  paciente_id INTEGER NULL REFERENCES pacientes (id) ON UPDATE CASCADE ON DELETE SET NULL,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'saude'
    CHECK (tipo IN ('saude', 'aviso', 'compromisso', 'medicamento', 'outro')),
  data_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  prioridade TEXT NOT NULL DEFAULT 'media'
    CHECK (prioridade IN ('baixa', 'media', 'alta')),
  status TEXT NOT NULL DEFAULT 'ativo'
    CHECK (status IN ('ativo', 'arquivado')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_inicio_data ON inicio_registros (data_registro DESC);
CREATE INDEX idx_inicio_tipo ON inicio_registros (tipo);
CREATE INDEX idx_inicio_status ON inicio_registros (status);
CREATE INDEX idx_inicio_usuario ON inicio_registros (usuario_id);

-- -----------------------------------------------------------------------------
-- Auditoria (LGPD — sem dados clínicos)
-- -----------------------------------------------------------------------------

CREATE TABLE auditoria_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE SET NULL,
  acao VARCHAR(80) NOT NULL,
  recurso VARCHAR(120) NOT NULL,
  recurso_id VARCHAR(64) NULL,
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  metadados_json JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_auditoria_usuario ON auditoria_logs (usuario_id);
CREATE INDEX idx_auditoria_acao ON auditoria_logs (acao);
CREATE INDEX idx_auditoria_recurso ON auditoria_logs (recurso);
CREATE INDEX idx_auditoria_created ON auditoria_logs (created_at);

-- -----------------------------------------------------------------------------
-- Triggers updated_at
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'perfis','menus','usuarios','permissoes_acesso',
    'hospitais_clinicas','farmacias','cuidadores','responsaveis',
    'medicos','pacientes','remedios','paciente_anamnese',
    'consultas','atendimentos_rotina','atendimento_execucoes','agenda_eventos',
    'inicio_registros'
  ]
  LOOP
    EXECUTE format(
      'CREATE TRIGGER trg_%s_updated_at
       BEFORE UPDATE ON %I
       FOR EACH ROW EXECUTE PROCEDURE set_updated_at()',
      t, t
    );
  END LOOP;
END $$;

-- =============================================================================
-- Seeds
-- =============================================================================

INSERT INTO perfis (id, nome, descricao) VALUES
  (1, 'Administrador', 'Acesso total ao sistema'),
  (2, 'Médico', 'Acesso clínico e catálogo de remédios'),
  (3, 'Atendente', 'Acesso operacional limitado'),
  (4, 'Cuidador', 'Execução de rotinas e confirmação de doses'),
  (5, 'Responsável', 'Acompanhamento familiar do paciente');

SELECT setval(pg_get_serial_sequence('perfis', 'id'), (SELECT MAX(id) FROM perfis));

INSERT INTO menus (id, titulo, rota, icone, ordem, menu_pai_id) VALUES
  (1,  'Dashboard', '/dashboard', 'layout-dashboard', 10, NULL),
  (2,  'Início', '/inicio', 'home', 15, NULL),
  (30, 'Saúde', NULL, 'heart-pulse', 20, NULL),
  (31, 'Pacientes', '/pacientes', 'user', 21, 30),
  (32, 'Médicos', '/medicos', 'stethoscope', 22, 30),
  (33, 'Remédios', '/remedios', 'pill', 23, 30),
  (34, 'Hospitais / Clínicas', '/hospitais', 'building', 24, 30),
  (35, 'Farmácias', '/farmacias', 'store', 25, 30),
  (36, 'Cuidadores', '/cuidadores', 'handshake', 26, 30),
  (37, 'Responsáveis', '/responsaveis', 'users', 27, 30),
  (50, 'Atividades', NULL, 'calendar', 50, NULL),
  (51, 'Agenda do Paciente', '/agenda', 'calendar', 51, 50),
  (52, 'Consultas e Sessões', '/consultas', 'stethoscope', 52, 50),
  (53, 'Medicamentos e Atendimento', '/rotina', 'pill', 53, 50),
  (54, 'Linha do Tempo', '/timeline', 'scroll-text', 54, 50),
  (10, 'Administração', NULL, 'settings', 90, NULL),
  (11, 'Usuários', '/usuarios', 'users', 91, 10),
  (12, 'Perfis', '/perfis', 'masks', 92, 10),
  (13, 'Acessos', '/acessos', 'key', 93, 10),
  (14, 'Auditoria', '/auditoria', 'scroll-text', 94, 10);

SELECT setval(pg_get_serial_sequence('menus', 'id'), (SELECT MAX(id) FROM menus));

INSERT INTO usuarios (id, nome, email, senha_hash, status, perfil_id) VALUES
  (
    1,
    'Administrador VitaLink',
    'admin@vitalink.local',
    '$2a$10$Mn5Qa0Jg8J.tmBH1PlO8lOGX2RRO2SQ0kQYk/JDTUqsVvXRhEZ.J.',
    'ativo',
    1
  );

SELECT setval(pg_get_serial_sequence('usuarios', 'id'), (SELECT MAX(id) FROM usuarios));

-- Administrador: CRUD completo
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 1, id, TRUE, TRUE, TRUE, TRUE FROM menus;

-- Médico
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 2, id, TRUE,
       CASE WHEN rota IN ('/inicio','/pacientes','/medicos','/remedios','/consultas','/agenda','/timeline','/rotina')
              OR titulo IN ('Saúde','Atividades','Dashboard','Início') THEN TRUE ELSE FALSE END,
       CASE WHEN rota IN ('/inicio','/pacientes','/medicos','/remedios','/consultas','/rotina') THEN TRUE ELSE FALSE END,
       CASE WHEN rota = '/inicio' THEN TRUE ELSE FALSE END
FROM menus WHERE id IN (1,2,30,31,32,33,34,35,50,51,52,53,54);

-- Atendente
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar) VALUES
  (3, 1, TRUE, FALSE, FALSE, FALSE),
  (3, 2, TRUE, TRUE, TRUE, TRUE),
  (3, 30, TRUE, FALSE, FALSE, FALSE),
  (3, 31, TRUE, FALSE, FALSE, FALSE),
  (3, 33, TRUE, FALSE, FALSE, FALSE);

-- Cuidador
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 4, id, TRUE,
       CASE WHEN rota IN ('/inicio','/rotina','/agenda','/timeline') THEN TRUE ELSE FALSE END,
       CASE WHEN rota IN ('/inicio','/rotina') THEN TRUE ELSE FALSE END,
       CASE WHEN rota = '/inicio' THEN TRUE ELSE FALSE END
FROM menus WHERE id IN (1,2,30,31,50,51,53,54);

-- Responsável
INSERT INTO permissoes_acesso (perfil_id, menu_id, pode_ler, pode_criar, pode_editar, pode_deletar)
SELECT 5, id, TRUE,
       CASE WHEN rota = '/inicio' THEN TRUE ELSE FALSE END,
       CASE WHEN rota = '/inicio' THEN TRUE ELSE FALSE END,
       CASE WHEN rota = '/inicio' THEN TRUE ELSE FALSE END
FROM menus WHERE id IN (1,2,50,51,54);
