/** Tipos de evento da área da saúde — ordem alfabética; "Outro" permanece no fim. */
export const EVENTOS_SAUDE = [
  'Acompanhamento ambulatorial',
  'Acompanhamento nutricional',
  'Acompanhamento pós-operatório',
  'Acupuntura',
  'Administração de medicamento',
  'Ambulatório de especialidade',
  'Análise clínica / coleta de sangue',
  'Aplicação de injeção',
  'Aplicação intramuscular',
  'Aplicação subcutânea',
  'Atendimento de enfermagem',
  'Atendimento domiciliar (home care)',
  'Atendimento em UBS / posto de saúde',
  'Atendimento em UPA',
  'Atendimento odontológico',
  'Atendimento psicológico',
  'Audiometria',
  'Avaliação cardiológica',
  'Avaliação de feridas',
  'Avaliação fonoaudiológica',
  'Avaliação geriátrica ampla',
  'Avaliação neurológica',
  'Avaliação oftalmológica',
  'Avaliação ortopédica',
  'Avaliação pneumológica',
  'Banho / higiene',
  'Biopsia',
  'Broncoscopia',
  'Cateterismo',
  'Check-up',
  'Cirurgia ambulatorial',
  'Cirurgia eletiva',
  'Colonoscopia',
  'Consulta',
  'Consulta de enfermagem',
  'Consulta de retorno',
  'Consulta pré-anestésica',
  'Controle de glicemia',
  'Controle de peso e medidas',
  'Controle de pressão arterial',
  'Cuidados paliativos',
  'Curativo',
  'Densitometria óssea',
  'Diálise peritoneal',
  'Eletrocardiograma (ECG)',
  'Eletroencefalograma (EEG)',
  'Emergência',
  'Endoscopia digestiva',
  'Exame de imagem (mamografia)',
  'Exame de imagem (raio-X)',
  'Exame de imagem (ressonância)',
  'Exame de imagem (tomografia)',
  'Exame de imagem (ultrassonografia)',
  'Exame de urina',
  'Exame laboratorial',
  'Fisioterapia',
  'Fonoterapia',
  'Hemodiálise',
  'Holter / MAPA',
  'Internação',
  'Internação domiciliar',
  'Monitoramento diário',
  'Nebulização',
  'Nutrição',
  'Odontologia',
  'Oxigenoterapia',
  'Pequena cirurgia',
  'Procedimento',
  'Pronto-socorro',
  'Psicologia / saúde mental',
  'Quimioterapia',
  'Radioterapia',
  'Reabilitação',
  'Reabilitação cardíaca',
  'Retirada de pontos',
  'Sessão de hemodiálise',
  'Terapia ocupacional',
  'Teste ergométrico',
  'Transfusão de sangue',
  'Transporte / remoção',
  'Triagem',
  'UTI / cuidados intensivos',
  'Vacinação',
  'Visita domiciliar',
  'Visita hospitalar',
].sort((a, b) => a.localeCompare(b, 'pt-BR'));

export const EVENT_TYPES = [...EVENTOS_SAUDE, 'Outro'];

/** Atividades da agenda do Início, com mapeamento para o backend. */
export const ATIVIDADES_INICIO = [
  { value: 'acupuntura', label: 'Acupuntura', tipo: 'compromisso' },
  { value: 'ambulatorial', label: 'Acompanhamento ambulatorial', tipo: 'compromisso' },
  { value: 'banho', label: 'Banho / higiene', tipo: 'saude' },
  { value: 'checkup', label: 'Check-up', tipo: 'compromisso' },
  { value: 'consulta', label: 'Consulta médica', tipo: 'compromisso' },
  { value: 'curativo', label: 'Curativo', tipo: 'saude' },
  { value: 'ecg', label: 'Eletrocardiograma (ECG)', tipo: 'compromisso' },
  { value: 'emergencia', label: 'Emergência / pronto-socorro', tipo: 'saude' },
  { value: 'enfermagem', label: 'Atendimento de enfermagem', tipo: 'saude' },
  { value: 'exame_imagem', label: 'Exame de imagem', tipo: 'compromisso' },
  { value: 'exame_lab', label: 'Exame laboratorial', tipo: 'compromisso' },
  { value: 'fisioterapia', label: 'Fisioterapia', tipo: 'compromisso' },
  { value: 'fono', label: 'Fonoterapia', tipo: 'compromisso' },
  { value: 'glicemia', label: 'Controle de glicemia', tipo: 'saude' },
  { value: 'hemodialise', label: 'Hemodiálise', tipo: 'compromisso' },
  { value: 'home_care', label: 'Atendimento domiciliar', tipo: 'saude' },
  { value: 'injecao', label: 'Aplicação de injeção', tipo: 'saude' },
  { value: 'internacao', label: 'Internação', tipo: 'saude' },
  { value: 'medicamento', label: 'Tomar remédio', tipo: 'medicamento' },
  { value: 'nebulizacao', label: 'Nebulização', tipo: 'saude' },
  { value: 'nutricao', label: 'Nutrição', tipo: 'compromisso' },
  { value: 'odontologia', label: 'Odontologia', tipo: 'compromisso' },
  { value: 'paliativo', label: 'Cuidados paliativos', tipo: 'saude' },
  { value: 'pressao', label: 'Medir pressão', tipo: 'saude' },
  { value: 'procedimento', label: 'Procedimento', tipo: 'compromisso' },
  { value: 'psicologia', label: 'Psicologia / saúde mental', tipo: 'compromisso' },
  { value: 'quimio', label: 'Quimioterapia', tipo: 'compromisso' },
  { value: 'radio', label: 'Radioterapia', tipo: 'compromisso' },
  { value: 'reabilitacao', label: 'Reabilitação', tipo: 'saude' },
  { value: 'retorno', label: 'Consulta de retorno', tipo: 'compromisso' },
  { value: 'terapia_ocupacional', label: 'Terapia ocupacional', tipo: 'compromisso' },
  { value: 'transporte', label: 'Transporte / remoção', tipo: 'outro' },
  { value: 'vacina', label: 'Vacinação', tipo: 'saude' },
  { value: 'visita', label: 'Visita domiciliar', tipo: 'saude' },
  { value: 'rotina', label: 'Outra rotina diária', tipo: 'outro' },
].sort((a, b) => a.label.localeCompare(b.label, 'pt-BR'));
