/**
 * VitaLink — seeder do catálogo de medicamentos (50+ / Farmácia Popular + polifarmácia).
 *
 * Uso:
 *   node src/seeds/catalogoMedicamentos.seeder.js
 *   npm run db:seed:catalogo
 *
 * Idempotente: cria a tabela e insere ON CONFLICT DO NOTHING.
 * Se já houver ≥ 2000 linhas, não reinsere.
 */
require('dotenv').config();

const fs = require('fs');
const path = require('path');
const { Client } = require('pg');
const { buildCatalogoMedicamentos } = require('./catalogoMedicamentos.data');

const cfg = {
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT || 5432),
  user: process.env.DB_USER || 'vitalink',
  password: process.env.DB_PASSWORD || 'vitalink_secret',
  database: process.env.DB_NAME || 'vitalink',
};

const DDL = `
CREATE TABLE IF NOT EXISTS catalogo_medicamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_comercial VARCHAR(180) NOT NULL,
  principio_ativo VARCHAR(180) NOT NULL,
  dosagem VARCHAR(80) NOT NULL,
  forma_farmaceutica VARCHAR(80) NOT NULL DEFAULT 'comprimido',
  classe_terapeutica VARCHAR(120) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT catalogo_medicamentos_uniq UNIQUE (nome_comercial, dosagem, forma_farmaceutica)
);
CREATE INDEX IF NOT EXISTS idx_catalogo_med_nome ON catalogo_medicamentos (nome_comercial);
CREATE INDEX IF NOT EXISTS idx_catalogo_med_pa ON catalogo_medicamentos (principio_ativo);
CREATE INDEX IF NOT EXISTS idx_catalogo_med_busca ON catalogo_medicamentos (nome_comercial, principio_ativo);
`;

function log(msg) {
  console.log(`[vitalink-seed-catalogo] ${msg}`);
}

function resolvePatchFile() {
  const candidates = [
    path.join(__dirname, '../../database/patch_catalogo_medicamentos.sql'),
    path.join(__dirname, '../../../database/patch_catalogo_medicamentos.sql'),
  ];
  return candidates.find((file) => fs.existsSync(file));
}

async function applyPermissions(client) {
  const patchFile = resolvePatchFile();
  if (!patchFile) return;
  const sql = fs.readFileSync(patchFile, 'utf8');
  try {
    await client.query(sql);
  } catch (err) {
    log(`AVISO ao aplicar patch de permissões: ${err.message}`);
  }
}

async function seedCatalogoMedicamentos(client) {
  await client.query(DDL);
  await applyPermissions(client);

  const countRes = await client.query(
    `SELECT COUNT(*)::int AS c FROM catalogo_medicamentos`
  );
  const existing = Number(countRes.rows[0]?.c || 0);
  const reset = (process.env.RESET_CATALOGO_MEDICAMENTOS || '') === 'true';
  if (existing >= 2000 && !reset) {
    log(`Catálogo já populado (${existing} apresentações).`);
    return { inserted: 0, total: existing };
  }
  if (reset && existing > 0) {
    await client.query('TRUNCATE catalogo_medicamentos RESTART IDENTITY');
    log(`Catálogo zerado (RESET_CATALOGO_MEDICAMENTOS=true).`);
  }

  const rows = buildCatalogoMedicamentos();
  log(`Geradas ${rows.length} apresentações. Inserindo (já havia ${existing})...`);

  const batchSize = 250;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const params = [];
    const values = batch.map((r, idx) => {
      const o = idx * 5;
      params.push(
        r.nome_comercial,
        r.principio_ativo,
        r.dosagem,
        r.forma_farmaceutica,
        r.classe_terapeutica
      );
      return `($${o + 1}, $${o + 2}, $${o + 3}, $${o + 4}, $${o + 5})`;
    });
    const result = await client.query(
      `INSERT INTO catalogo_medicamentos
         (nome_comercial, principio_ativo, dosagem, forma_farmaceutica, classe_terapeutica)
       VALUES ${values.join(', ')}
       ON CONFLICT (nome_comercial, dosagem, forma_farmaceutica) DO NOTHING`,
      params
    );
    inserted += result.rowCount || 0;
  }

  const totalRes = await client.query(
    `SELECT COUNT(*)::int AS c FROM catalogo_medicamentos`
  );
  const total = Number(totalRes.rows[0]?.c || 0);
  log(`OK. Inseridas ${inserted}. Total no catálogo: ${total}.`);
  return { inserted, total };
}

async function main() {
  const client = new Client({
    ...cfg,
    connectionTimeoutMillis: 15000,
    statement_timeout: 120000,
  });
  await client.connect();
  log(`Conectado em ${cfg.host}:${cfg.port}/${cfg.database}`);
  try {
    await seedCatalogoMedicamentos(client);
  } finally {
    await client.end().catch(() => {});
  }
}

if (require.main === module) {
  main().catch((err) => {
    console.error(`[vitalink-seed-catalogo] ERRO: ${err.message}`);
    process.exit(1);
  });
}

module.exports = { seedCatalogoMedicamentos };
